config/routes.rb
Rails.application.routes.draw do
  resources :icons
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/icon.rb
class Icon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  before_action :set_icon, only: [:show, :edit, :update, :destroy]

  # GET /icons
  # GET /icons.json
  def index
    @icons = Icon.all
  end

  # GET /icons/1
  # GET /icons/1.json
  def show
  end

  # GET /icons/new
  def new
    @icon = Icon.new
  end

  # GET /icons/1/edit
  def edit
  end

  # POST /icons
  # POST /icons.json
  def create
    @icon = Icon.new(icon_params)

    respond_to do |format|
      if @icon.save
        format.html { redirect_to @icon, notice: 'Icon was successfully created.' }
        format.json { render :show, status: :created, location: @icon }
      else
        format.html { render :new }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icons/1
  # PATCH/PUT /icons/1.json
  def update
    respond_to do |format|
      if @icon.update(icon_params)
        format.html { redirect_to @icon, notice: 'Icon was successfully updated.' }
        format.json { render :show, status: :ok, location: @icon }
      else
        format.html { render :edit }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icons/1
  # DELETE /icons/1.json
  def destroy
    @icon.destroy
    respond_to do |format|
      format.html { redirect_to icons_url, notice: 'Icon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icon
      @icon = Icon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def icon_params
      params.fetch(:icon, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/views/icons/_form.html.erb
<%= form_for(icon) do |f| %>
  <% if icon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(icon.errors.count, "error") %> prohibited this icon from being saved:</h2>

      <ul>
      <% icon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/icons/edit.html.erb
<h1>Editing Icon</h1>

<%= render 'form', icon: @icon %>

<%= link_to 'Show', @icon %> |
<%= link_to 'Back', icons_path %>

app/views/icons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Icons</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @icons.each do |icon| %>
      <tr>
        <td><%= link_to 'Show', icon %></td>
        <td><%= link_to 'Edit', edit_icon_path(icon) %></td>
        <td><%= link_to 'Destroy', icon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Icon', new_icon_path %>

app/views/icons/new.html.erb
<h1>New Icon</h1>

<%= render 'form', icon: @icon %>

<%= link_to 'Back', icons_path %>

app/views/icons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_icon_path(@icon) %> |
<%= link_to 'Back', icons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twicon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>